{% set name = "tritonclient" %}
{% set version = "2.34.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}
source:
  url: https://files.pythonhosted.org/packages/49/4f/3513e96dab662eca882d0f917d7a04a775b13196433ab20d5a45b070cd9b/tritonclient-2.34.0-py3-none-any.whl
  sha256: 876ff68aba141eeb047fdc1eeeebef42c47126c40cbd3f92b3800c8afe55dbcc

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python
        - pip
      run:
        - numpy>=1.19.1
        - python-rapidjson>=0.9.1
    test:
      imports:
        - tritonclient
        - tritonclient.utils
      requires:
        - pip
      commands:
        - pip check
  - name: {{ name }}-http
    build:
      noarch: python
    requirements:
      host:
        - python
        - pip
        - {{ pin_subpackage('tritonclient', exact=True) }}
      run:
        - {{ pin_subpackage('tritonclient', exact=True) }}
        - geventhttpclient>=1.4.4,<=2.0.2
        - aiohttp>=3.8.1,<4.0.0
    test:
      imports:
        - tritonclient.http
      requires:
        - pip
      commands:
        - pip check
  - name: {{ name }}-grpc
    build:
      noarch: python
    requirements:
      host:
        - python
        - pip
        - {{ pin_subpackage('tritonclient', exact=True) }}
      run:
        - {{ pin_subpackage('tritonclient', exact=True) }}
        - grpcio>=1.41.0
        - protobuf>=3.5.0,<4
        - packaging>=14.1
    test:
      imports:
        - tritonclient.grpc
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://developer.nvidia.com/nvidia-triton-inference-server
  license: BSD-3-Clause
  license_file: tritonclient-{{ version }}.dist-info/LICENSE.txt
  summary: Python client library and utilities for communicating with Triton Inference Server.

extra:
  recipe-maintainers:
    - janjagusch
